# Generated by Django 4.2.2 on 2023-06-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acidez_fixa', models.IntegerField()),
                ('acidez_volátil', models.IntegerField()),
                ('acido_cítrico', models.IntegerField()),
                ('acucar_residual', models.IntegerField()),
                ('cloretos', models.IntegerField()),
                ('dióxido_de_enxofre_livre', models.IntegerField()),
                ('dióxido_de_enxofre_total', models.IntegerField()),
                ('densidade', models.IntegerField()),
                ('pH', models.IntegerField()),
                ('sulfatos', models.IntegerField()),
                ('álcool', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Carros',
        ),
    ]
